### ISSUE TITLE
Regenerate the C program 

### ISSUE THREAD

**Issue by Biplab-313** [Biplab-313/C_language_Q-A#1]
### Palindrome Number Program

`
#include <stdio.h>

int main() {
    int num, reverse = 0, remainder, original;

    // Input a number
    printf("Enter a number: ");
    scanf("%d", &num);

    original = num;

    // Reverse the number
    while (num != 0) {
        remainder = num % 10;
        reverse = reverse * 10 + remainder;
        num /= 10;
    }

    // Check if palindrome
    if (original == reverse)
        printf("%d is a palindrome number.\n", original);
    else
        printf("%d is not a palindrome number.\n", original);

    return 0;
}
`

Create Palindrome String Program  and upgrade the Palindrome Number Program

> Not create a basic one

**Comment by SnehaghoshBarsha444** [comment]
@Biplab-313 sir ,
I'm interested in it
Can you assign me?
