### ISSUE TITLE
Project : Write a C program to implement a game of "Snake, Water, Gun"

### ISSUE THREAD

**Issue by Biplab-313** [Biplab-313/C_language_Q-A#5]
### Project 

**Write a C program to implement a game of "Snake, Water, Gun" where the user can play against the computer. The program should generate a random choice for the computer and allow the user to input their choice. The program should then determine the winner based on the game's rules and display the result.**

> In this game, the rules are as follows :
- Snake beats Water
- Water beats Gun
- Gun beats Snake
- If both the user and the computer choose the same option, it's a draw.

**Comment by SnehaghoshBarsha444** [comment]
@Biplab-313  sir ,
I would like to write this program in C .
Kindly assign me .

**Comment by Biplab-313** [comment]
@SnehaghoshBarsha444 very nice
well done

As you generate a perfect code for this issue  , I'm going to accept your PR asap
Thank you . 
Happy Coding
